name: JIRA consistency

on:
  repository_dispatch:
  issues:
    types: ['milestoned', 'demilestoned']
  pull_request:
    types: ['opened', 'edited', 'synchronize', 'reopened', 'closed']
  #schedule:
  #  - cron: '5 * * * *'

jobs:
  jira_pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'JIRA consistency'
        uses: cchantep/probot-jira@ghaction-1.0.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PROJECT_NAME: 'PAP'
          PERSONAL_TOKEN_VALUE: ${{ secrets.PERSONAL_TOKEN_VALUE }}
          PERSONAL_TOKEN_USER: 'cchantep'
